pipeline: "niftymic"
docker: 
  cmd: "docker run --gpus '\"device=0\"' <mount> renbem/niftymic 
    niftymic_run_reconstruction_pipeline
    --filenames <input_stacks>
    --filenames-masks <input_masks>
    --dir-output <output_dir>"
singularity:
  cmd: "singularity exec --bind /gpfs:/gpfs --nv  
    <singularity_path>/niftymic_upf_latest.sif
    niftymic_run_reconstruction_pipeline
    --filenames <input_stacks>
    --filenames-masks <input_masks>
    --dir-output <output_dir>"
path_to_output: "recon_template_space/srr_template.nii.gz"