defaults:
  - preprocessing/default
  - reconstruction/nesvor
  - segmentation/bounti
  - _self_
container: "singularity"
singularity_path: "/scratch/gauzias/softs/fetpype_singularity_images"
singularity_mount: "/scratch/:/scratch/"
#preprocessing:
#  disable_cropping: null
reconstruction:
  output_resolution: 0.5
save_graph: False
